// Generated by CoffeeScript 1.9.1
(function() {
  var SignatureManager, fs, signature;

  fs = require('fs');

  signature = function(options) {
    var signatureManager;
    signatureManager = new SignatureManager(options);
    return function(options, done) {
      return signatureManager.compile(options, done);
    };
  };

  SignatureManager = (function() {
    function SignatureManager(signature) {
      if (typeof signature === "object") {
        this.signature = signature.signature, this.signatureFile = signature.signatureFile, this.applyTo = signature.applyTo, this.separator = signature.separator;
      } else {
        this.signature = signature;
        this.signatureFile = null;
        if (fs.existsSync(this.signature)) {
          this.signatureFile = this.signature;
          this.signature = null;
        }
        this.separator = "\n--\n";
      }
      if (this.applyTo == null) {
        this.applyTo = {
          markdown: (function(_this) {
            return function(text, signature) {
              return text + _this.separator + signature;
            };
          })(this),
          html: (function(_this) {
            return function(text, signature) {
              return text + _this.separator + signature;
            };
          })(this),
          text: (function(_this) {
            return function(text, signature) {
              return text + _this.separator + signature;
            };
          })(this)
        };
      }
    }

    SignatureManager.prototype.compile = function(mail, done) {
      var key, options, ref, value;
      options = mail.data;
      if (options.signature) {
        signature = options.signature;
      } else {
        if (this.signatureFile) {
          signature = fs.readSync(this.signatureFile);
        } else {
          signature = this.signature;
        }
      }
      if (typeof signature === "object") {
        for (key in signature) {
          value = signature[key];
          if (!(key in options)) {
            continue;
          }
          if (value instanceof Function) {
            options[key] = value.call(this, options[key]);
          } else {
            options[key] += this.separator + value;
          }
        }
      } else {
        ref = this.applyTo;
        for (key in ref) {
          value = ref[key];
          if (!(key in options)) {
            continue;
          }
          options[key] = this.applyTo[key](options[key], signature);
        }
      }
      return done();
    };

    return SignatureManager;

  })();

  module.exports = {
    signature: signature,
    SignatureManager: SignatureManager
  };

}).call(this);
